### DISCUSSION TITLE
Issue with Google Integration in Twenty CRM - Google Sync Failed

### DISCUSSION THREAD

**Discussion by ralfdigitalagency** [twentyhq/twenty#10270] [Unsolvable issues]
![Screenshot 2025-02-17 184049](https://github.com/user-attachments/assets/813e8340-1312-4546-a9b3-fd315c7ef8f5)

![Screenshot 2025-02-17 183915](https://github.com/user-attachments/assets/9f91c0cc-d009-4840-bfc7-86e89dfc61a4)

![Screenshot 2025-02-17 183338](https://github.com/user-attachments/assets/55ff458e-0f97-41bf-b188-862f093d0015)

Hello everyone,

I’m trying to integrate Google Calendar and Google Gmail with Twenty CRM following the official self-hosting guide: [Setup Messaging & Calendar Sync](https://twenty.com/developers/section/self-hosting/setup#setup-messaging-&-calendar-sync). I’ve completed the following steps:

-Created a project in Google Cloud Console.
-Enabled the required APIs (Google Calendar API, Gmail API, and Google People API).
-Created OAuth credentials and obtained the Client ID and Client Secret.
-Configured the required scopes in Google Cloud Console:
   +https://www.googleapis.com/auth/calendar.events
   +https://www.googleapis.com/auth/gmail.readonly
   +https://www.googleapis.com/auth/userinfo.email

Problem 1: Where to add the Scopes?
The guide is unclear on whether the scopes should be added to the .env file in the project or if they should just be configured in Google Cloud Console. I’ve added them in Google Cloud Console, but I’m unsure if I need to modify anything in the Twenty CRM configuration files as well.

Problem 2: "Connect to Google" Button not Appearing
Even though everything seems configured correctly, I can’t see the "Connect to Google" button in the Twenty CRM settings. Is there something I need to do to make it visible?

What I’ve tried so far:

Restarted the Docker container for Twenty CRM.
Checked the logs, and there don’t seem to be any obvious errors.
Double-checked all configurations in Google Cloud Console and Twenty CRM, but the button still doesn’t appear.

Details:
Twenty CRM version: v0.42.5
Docker version: latest
Operating system of the server: Ubuntu 24.04

Anyone with experience integrating Google into Twenty CRM, your help would be greatly appreciated!

**Comment by ralfdigitalagency** [comment]
![Screenshot 2025-02-17 191458](https://github.com/user-attachments/assets/007df275-ca94-407a-9166-0d5b2ea9c100)

UPDATE

I added this code to the docker-compose.yml file:

 # Configurazione Google OAuth
      CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE>      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      AUTH_GOOGLE_CALLBACK_URL: ${AUTH_GOOGLE_CALLBACK_URL}
      AUTH_GOOGLE_APIS_CALLBACK_URL: ${AUTH_GOOGLE_APIS_CALLBACK_U>

and got this (see attachment), did I configured it right?

**Comment by byayex** [comment]
Have a similar issue, everything is configured like above but i get an „sync failed“ text on my account but no error logs.

**Comment by naiki-devlab** [comment]
I do have similar issue with a self hosted docker deployment on my ubuntu VPS. 

ive set the google related env vars from the admin panel as per the documentation page. 
i can go throught the entire oauth auth flow and i get redirected as should be, but the sync is still failling

please provide fix, documentation or bounty for this problem

**Comment by Rixita** [comment]
Hi all, I have the same issue as the others in this thread are having. Would be great if there was a solution for this issue.
Thanks.

**Comment by salesbay** [comment]
We upgraded to version 0.55.6, but the issue persists. We had to manually adjust the settings to get it to work, yet we still frequently experience timeouts.

**Reply by Rixita** [reply]
Hi @salesbay, could you please elaborate on what you mean by "manually adjust the settings to get it to work"? I’d like to try that as a temporary solution.
thx.

**Comment by byayex** [comment]
I fixed my error by running the migration commands aswell as rerunning the cron commands

**Reply by Rixita** [reply]
@byayex Do you run in docker?  could you share which commands you used for the migration commands? That would be great, thanks

**Reply by byayex** [reply]
Yes I run in docker. I used 
`yarn database:migrate:prod
yarn command:prod upgrade`

and the cron jobs 

`# from your worker container
yarn command:prod cron:messaging:messages-import
yarn command:prod cron:messaging:message-list-fetch
yarn command:prod cron:calendar:calendar-event-list-fetch
yarn command:prod cron:calendar:calendar-events-import
yarn command:prod cron:messaging:ongoing-stale
yarn command:prod cron:calendar:ongoing-stale
yarn command:prod cron:workflow:automated-cron-trigger`

This fixed it for me.

**Comment by alembical** [comment]
**Hey**,

Had the same issue - the worker service needs identical environment variables as the main service (except for command). Here's the fix:

```yaml
version: '3.8'
services:
  twenty:
    image: 'twentycrm/twenty:${TAG:-latest}'
    environment:
      - SERVER_URL=$SERVICE_FQDN_TWENTY
      - FRONT_BASE_URL=$SERVICE_FQDN_TWENTY
      # ... (other vars) ...
  
  worker:
    image: 'twentycrm/twenty:${TAG:-latest}'
    # --- Ensure ALL environment vars match `twenty` ---
    environment:
      - SERVER_URL=$SERVICE_FQDN_TWENTY  # Must match
      - FRONT_BASE_URL=$SERVICE_FQDN_TWENTY  # Must match
      # ... (include ALL other vars from `twenty`) ...
    command: 'yarn worker:prod'
    depends_on:
      twenty:
        condition: service_healthy

  # ... (db, redis, volumes config) ...
```

**Key Notes:**  
1. The `worker` **must** mirror `twenty`’s `environment` section to avoid issues.  
2. Only `command` and `depends_on` should differ.
