### DISCUSSION TITLE
Deploy Twenty using docker compose

### DISCUSSION THREAD

**Discussion by amirulabu** [twentyhq/twenty#3598] [Engineering vision]
I would appreciate it if anyone in the community that attempted to run twenty using docker compose can share their `compose.yaml` file.

**Comment by amirulabu** [comment]
Nevermind, this is my attempt. I think i need to add more [environment variables](https://docs.twenty.com/start/self-hosting/environment-variables) to make it ready for production. 

```yaml
services:
  web:
    image: twentycrm/twenty-front:0.2.3
    ports:
      - 13000:3000
    environment:
      - REACT_APP_SERVER_BASE_URL=http://localhost:13001

  server:
    image: twentycrm/twenty-server:0.2.3
    ports:
      - 127.0.0.1:13001:3000
    networks:
      - backend
    command: "sh -c ./scripts/render-run.sh"
    depends_on:
      - postgres
    environment:
      - FRONT_BASE_URL=http://localhost:13001
      - ACCESS_TOKEN_SECRET=07f77380a28a585365eb9a5adfc9163b7e0a4e2c870cf011d384784948b89a531566be9f9d295eda4b32a560cc29ddf6272099c15f38c1bcacddc420da0f727c
      - LOGIN_TOKEN_SECRET=07f77380a28a585365eb9a5adfc9163b7e0a4e2c870cf011d384784948b89a531566be9f9d295eda4b32a560cc29ddf6272099c15f38c1bcacddc420da0f727c
      - REFRESH_TOKEN_SECRET=07f77380a28a585365eb9a5adfc9163b7e0a4e2c870cf011d384784948b89a531566be9f9d295eda4b32a560cc29ddf6272099c15f38c1bcacddc420da0f727c
      - PG_DATABASE_HOST=postgres
      - PG_DATABASE_PORT=5432

  postgres:
    image: twentycrm/twenty-postgres:0.2.3
    networks:
      - backend
    ports:
      - 127.0.0.1:15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default

networks:
  backend:

```
