### ISSUE TITLE
Error when opening data model settings

### ISSUE THREAD

**Issue by krystof-k** [twentyhq/twenty#10602]
## Bug Description

I get `Instance id is not provided and cannot be found in context` when opening data model settings:

https://github.com/user-attachments/assets/975151ae-e457-4e3e-a587-8cdb156801d7

## Expected behavior

It opens the settings.

## Technical inputs

Version 0.43.1 (self-hosted).

**Comment by flyotlin** [comment]
Same here, any idea?

**Comment by RaghavJha1965** [comment]
Is it still giving out the same result ? I check the data model settings repeatedly, but I didn't encounter the issue.

**Comment by flyotlin** [comment]
I set up twenty by docker compose, the version is "0.43.3".

This error happened when:
- I clicked "Settings" of any data model.
- I clicked some specific field of a data model, like "Name" in "People".

docker compose, basically the same as that of documentation:
```yaml
name: twenty

services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"

  server:
    image: twentycrm/twenty:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    ports:
      - "3000:3000"
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/default
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

      #STORAGE_TYPE: ${STORAGE_TYPE}
      #STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      #STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      #STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      EMAIL_DRIVER: smtp
      EMAIL_SMTP_HOST: mailpit-twenty
      EMAIL_SMTP_PORT: 1025

      APP_SECRET: ${APP_SECRET}
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:${TAG:-latest}
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/default
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      DISABLE_DB_MIGRATIONS: "true" # it already runs on the server

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      EMAIL_DRIVER: smtp
      EMAIL_SMTP_HOST: mailpit-twenty
      EMAIL_SMTP_PORT: 1025

      APP_SECRET: ${APP_SECRET}
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD:-postgres}
    healthcheck:
      test: pg_isready -U ${PG_DATABASE_USER:-postgres} -h localhost -d postgres
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis
    restart: always

  mailpit-twenty:
    image: axllent/mailpit
    container_name: mailpit-twenty
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  docker-data:
  db-data:
  server-local-data:
```
