### ISSUE TITLE
Google connected account does not work as expected

### ISSUE THREAD

**Issue by israpasos** [twentyhq/twenty#11135]
## Bug Description

**Environment:** Self-hosted via Coolify
**Guide:** https://twenty.com/developers/section/self-hosting/setup

**APIs Enabled:**
<img width="477" alt="Image" src="https://github.com/user-attachments/assets/18f2f2fe-8a1d-47a1-be00-4e5cfb3ae63a" />
<img width="471" alt="Image" src="https://github.com/user-attachments/assets/33494cbd-5a49-4840-a01f-92cfabd8ffba" />
<img width="533" alt="Image" src="https://github.com/user-attachments/assets/642b170d-bcbe-48ee-b2e6-0f32c99eb1bb" />

**Redirects Added:**
<img width="317" alt="Image" src="https://github.com/user-attachments/assets/240616dc-278c-4c63-9f22-e8596dea3716" />

**Scopes Added:**
<img width="706" alt="Image" src="https://github.com/user-attachments/assets/dca4643c-adec-4bfa-a42a-dd6480c1f657" />

**Issue:**
Importing "hangs" in /settings/accounts:
<img width="518" alt="Image" src="https://github.com/user-attachments/assets/d8648069-7e0e-44e9-bd36-7129d1293339" />

Emails don't load:
<img width="406" alt="Image" src="https://github.com/user-attachments/assets/9010f325-c622-481b-9ad2-a4764843d25f" />

Unlike in the cloud version that does:
<img width="554" alt="Image" src="https://github.com/user-attachments/assets/1b7af5bb-3e14-4ffe-a019-d41bd38b8acc" />

Weirdly contacts were in fact imported:
<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/bbafca4f-10ee-4b98-9a5d-98188e24deb9" />

Worker log:
```
2025-03-24T23:00:00.267854455Z [Nest] 34  - 03/24/2025, 11:00:00 PM     LOG [MessagingMessagesImportService] Messaging import for workspace <workspace-uuid> and account <account-uuid> starting...
2025-03-24T23:00:00.570419576Z Exception Captured
2025-03-24T23:00:00.570826624Z   undefined
2025-03-24T23:00:00.580120166Z   [
2025-03-24T23:00:00.580139862Z     GaxiosError: <!DOCTYPE html>
2025-03-24T23:00:00.580156984Z     <html lang="en">
2025-03-24T23:00:00.580160803Z       <meta charset="utf-8">
2025-03-24T23:00:00.580164460Z       <meta name="viewport" content="initial-scale=1, minimum-scale=1, width=device-width">
2025-03-24T23:00:00.580168177Z       <title>Error 403 (Forbidden)!!1</title>
...
2025-03-24T23:00:00.580195778Z       <p><b>403.</b> <ins>That’s an error.</ins>
2025-03-24T23:00:00.580199806Z       <p>Your client does not have permission to get URL <code>/v1/people/me</code> from this server.  <ins>That’s all we know.</ins>
...
2025-03-24T23:00:00.580225153Z         at async GoogleEmailAliasManagerService.getHandleAliases (.../google-email-alias-manager.service.js:30:32)
2025-03-24T23:00:00.580227568Z         at async EmailAliasManagerService.refreshHandleAliases (.../email-alias-manager.service.js:34:33)
2025-03-24T23:00:00.580229832Z         at async MessagingMessagesImportService.processMessageBatchImport (.../messaging-messages-import.service.js:89:13)
2025-03-24T23:00:00.580232147Z         at async MessagingMessagesImportJob.handle (.../messaging-messages-import.job.js:63:9)
...
2025-03-24T23:00:00.580289785Z         url: 'https://people.googleapis.com/v1/people/me?personFields=emailAddresses',
...
2025-03-24T23:00:00.580312158Z       code: '403'
2025-03-24T23:00:00.580316136Z   ]
```

## Expected behavior

Twenty should not hang on importing contacts from Google and emails should dsplay correctly.

## Technical inputs

docker-compose:
```
services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"

  twenty:
    image: 'twentycrm/twenty:latest'
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    environment:
      - SERVICE_FQDN_TWENTY_3000
      - SERVER_URL=$SERVICE_FQDN_TWENTY
      - FRONT_BASE_URL=$SERVICE_FQDN_TWENTY
      - ENABLE_DB_MIGRATIONS=true
      - CACHE_STORAGE_TYPE=${CACHE_STORAGE_TYPE:-redis}
      - REDIS_URL=redis://redis:6379
      - API_RATE_LIMITING_TTL=${API_RATE_LIMITING_TTL:-100}
      - API_RATE_LIMITING_LIMIT=${API_RATE_LIMITING_LIMIT:-100}
      - APP_SECRET=${SERVICE_BASE64_32_SECRET}
      - POSTGRES_ADMIN_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - PG_DATABASE_URL=postgres://postgres:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/default
      - IS_SIGN_UP_DISABLED=${IS_SIGN_UP_DISABLED:-false}
      - PASSWORD_RESET_TOKEN_EXPIRES_IN=${PASSWORD_RESET_TOKEN_EXPIRES_IN:-5m}
      - STORAGE_TYPE=${STORAGE_TYPE:-local}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_NAME=${STORAGE_S3_NAME}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      - STORAGE_S3_ACCESS_KEY_ID=${STORAGE_S3_ACCESS_KEY_ID}
      - STORAGE_S3_SECRET_ACCESS_KEY=${STORAGE_S3_SECRET_ACCESS_KEY}
      - MESSAGE_QUEUE_TYPE=${MESSAGE_QUEUE_TYPE:-pg-boss}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - EMAIL_SYSTEM_ADDRESS=${EMAIL_SYSTEM_ADDRESS}
      - EMAIL_DRIVER=${EMAIL_DRIVER:-logger}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - SIGN_IN_PREFILLED=false
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
      - MESSAGING_PROVIDER_GMAIL_ENABLED=true
      - CALENDAR_PROVIDER_GOOGLE_ENABLED=true
      - AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
      - AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}
      - AUTH_GOOGLE_CALLBACK_URL=${AUTH_GOOGLE_CALLBACK_URL}
      - AUTH_GOOGLE_APIS_CALLBACK_URL=${AUTH_GOOGLE_APIS_CALLBACK_URL}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/healthz"]
      interval: 2s
      timeout: 10s
      retries: 15

  worker:
    image: 'twentycrm/twenty:latest'
    command: ["yarn", "worker:prod"]
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    environment:
      # same as "twenty" service above
      - SERVICE_FQDN_TWENTY_3000
      - SERVER_URL=$SERVICE_FQDN_TWENTY
      - FRONT_BASE_URL=$SERVICE_FQDN_TWENTY
      - ENABLE_DB_MIGRATIONS=true
      - CACHE_STORAGE_TYPE=${CACHE_STORAGE_TYPE:-redis}
      - REDIS_URL=redis://redis:6379
      - API_RATE_LIMITING_TTL=${API_RATE_LIMITING_TTL:-100}
      - API_RATE_LIMITING_LIMIT=${API_RATE_LIMITING_LIMIT:-100}
      - APP_SECRET=${SERVICE_BASE64_32_SECRET}
      - POSTGRES_ADMIN_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - PG_DATABASE_URL=postgres://postgres:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/default
      - IS_SIGN_UP_DISABLED=${IS_SIGN_UP_DISABLED:-false}
      - PASSWORD_RESET_TOKEN_EXPIRES_IN=${PASSWORD_RESET_TOKEN_EXPIRES_IN:-5m}
      - STORAGE_TYPE=${STORAGE_TYPE:-local}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_NAME=${STORAGE_S3_NAME}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      - STORAGE_S3_ACCESS_KEY_ID=${STORAGE_S3_ACCESS_KEY_ID}
      - STORAGE_S3_SECRET_ACCESS_KEY=${STORAGE_S3_SECRET_ACCESS_KEY}
      - MESSAGE_QUEUE_TYPE=${MESSAGE_QUEUE_TYPE:-pg-boss}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - EMAIL_SYSTEM_ADDRESS=${EMAIL_SYSTEM_ADDRESS}
      - EMAIL_DRIVER=${EMAIL_DRIVER:-logger}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - SIGN_IN_PREFILLED=false
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}
      - MESSAGING_PROVIDER_GMAIL_ENABLED=true
      - CALENDAR_PROVIDER_GOOGLE_ENABLED=true
      - AUTH_GOOGLE_ENABLED=true
      - AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
      - AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}
      - AUTH_GOOGLE_CALLBACK_URL=${AUTH_GOOGLE_CALLBACK_URL}
      - AUTH_GOOGLE_APIS_CALLBACK_URL=${AUTH_GOOGLE_APIS_CALLBACK_URL}
    depends_on:
      postgres:
        condition: service_healthy
      twenty:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=default
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 20s
      retries: 10
    restart: always

  redis:
    image: 'redis:latest'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 20s
      retries: 10
    restart: always

volumes:
  docker-data:
  db-data:
  server-local-data:
  redis-data:
```
