### ISSUE TITLE
docker -> local directory for volume db-data -> no user login

### ISSUE THREAD

**Issue by patschwork** [twentyhq/twenty#5880]
## Bug Description

When using a local directory for storing the db-data content, you can't login after fresh setup. 
The hint here doesn't work: https://twenty.com/developers/section/self-hosting/docker-compose#not-able-to-login

**Example:** 
# Excerpt from `docker-compose.yml`
```yml

  db:
    image: twentycrm/twenty-postgres:${TAG}
    volumes:
      - ./db-data:/bitnami/postgresql.  # local directory with file permissions for UID 1001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: pg_isready -U twenty -d default
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  docker-data:
  # db-data:
  server-local-data:
```

## Expected behavior

Login/signup is possible as if it would be a docker managed volume

## Workaround

It will work, when set the parameter `ENABLE_DB_MIGRATIONS: "true"` in the worker section of `docker-compose.yml`

**Example:** 
```yml
  worker:
    image: twentycrm/twenty:${TAG}
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}

      ENABLE_DB_MIGRATIONS: "true" # it already runs on the server #--------> set this to "true"

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}
      TELEMETRY_ENABLED: false. # will this work?!
      EMAIL_SMTP_HOST: 192.168.178.99 # does not work :-( -> https://twenty.com/developers/section/self-hosting/self-hosting-var#email-smtp-server-configuration-examples / smtp4dev
      EMAIL_SMTP_PORT: 2525 # does not work :-(  / smtp4dev
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always
```
