### ISSUE TITLE
Cache related error after upgrading from 0.22.0 to 0.23.1

### ISSUE THREAD

**Issue by estan** [twentyhq/twenty#6610]
## Bug Description

After bumping our 0.22.0 Docker Compose installation to 0.23.1 and running `docker-compose up -d`, the application seems to have been migrated and come up normally. However, when visiting the site, it's not loading any content:

![bild](https://github.com/user-attachments/assets/152a527c-acba-4cf8-a226-9bd4438a773a)

Upgrading in this way has worked in the past.

## Expected behavior

Content should be loaded.

## Technical inputs

Console in Firefox Developer Tools is showing:

```
GET
https://twenty.orexplore.se/files/workspace-logo/original/014f5e46-697c-4820-a074-6f53f028ac60.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmF0aW9uX2RhdGUiOiIyMDI0LTA4LTEyVDEwOjAzOjEyLjU3OFoiLCJ3b3Jrc3BhY2VfaWQiOiIzMGVlMDY2ZC0xODYxLTQ5ZTgtODMzMS0wNzFkZGIzZDAxYTkiLCJpYXQiOjE3MjMzNzA1OTIsImV4cCI6MTcyMzM3MjM5Mn0.HlmKbH3gL_C0YB8Jl3-ZXJJVPEe-CeD562dBLkUkowI
[HTTP/1.1 503 Service Unavailable 83ms]

XHRPOST
https://twenty.orexplore.se/graphql
[HTTP/1.1 503 Service Unavailable 5ms]

XHRPOST
https://twenty.orexplore.se/graphql
[HTTP/1.1 503 Service Unavailable 23ms]

XHRPOST
https://twenty.orexplore.se/graphql
[HTTP/1.1 503 Service Unavailable 19ms]

XHRPOST
https://twenty.orexplore.se/graphql
[HTTP/1.1 503 Service Unavailable 17ms]

Uncaught (in promise) ApolloError: Response not successful: Received status code 503
    t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:343
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    a https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    G_ https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    G_ https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    HJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    promise callback*c https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    onError https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    sQt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    timerId https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    setTimeout handler*e.prototype.scheduleRetry https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    HJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    promise callback*c https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    onError https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    sQt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    zJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    PJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*PJt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    YVe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    complete https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    start https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    getObservableFromLink https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:349
    Qyr https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    n2r https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    setTimeout handler*n2r/< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    RH https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    N8 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    r2e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    vv https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:45
    r4t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    y4 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    lNe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    T https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
    R https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
    EventHandlerNonNull* https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
    <anonymous> https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
Caused by: ServerError: Response not successful: Received status code 503
    due https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    Hje https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    pue https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    promise callback*pue/< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    timerId https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    setTimeout handler*e.prototype.scheduleRetry https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    HJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    promise callback*c https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    onError https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    sQt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    zJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    PJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*PJt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    YVe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    complete https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    start https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    getObservableFromLink https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:349
    Qyr https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    n2r https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    setTimeout handler*n2r/< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    RH https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    N8 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    r2e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    vv https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:45
    r4t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    y4 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    lNe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    T https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
    R https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
    EventHandlerNonNull* https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
    <anonymous> https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:32
index-DTUxZWpZ.js:343:152
XHRPOST
https://twenty.orexplore.se/graphql
[HTTP/1.1 503 Service Unavailable 34ms]

XHRPOST
https://twenty.orexplore.se/graphql
[HTTP/1.1 503 Service Unavailable 17ms]

Uncaught (in promise) ApolloError: Response not successful: Received status code 503
    t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:343
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    a https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    G_ https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    G_ https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    HJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    promise callback*c https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    onError https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    sQt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    timerId https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    setTimeout handler*e.prototype.scheduleRetry https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    HJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    promise callback*c https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    onError https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    sQt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    zJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    PJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*PJt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    YVe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    complete https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    start https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    getObservableFromLink https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:349
    Qyr https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    n2r https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    setTimeout handler*n2r/< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    RH https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    N8 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    r4t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    y4 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    r2e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    vv https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:45
    xd https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    xd https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
Caused by: ServerError: Response not successful: Received status code 503
    due https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    Hje https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    pue https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    promise callback*pue/< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    timerId https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    setTimeout handler*e.prototype.scheduleRetry https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    HJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    promise callback*c https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    onError https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    $je https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    _G https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    error https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    sQt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*sQt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    try https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    zJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    PJt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    promise callback*PJt/</< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    YVe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:1020
    e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    subscribe https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    complete https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    start https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:342
    getObservableFromLink https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    QFt https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    l https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    Su https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:293
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    mutate https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:347
    s https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:349
    Qyr https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    n2r https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    setTimeout handler*n2r/< https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:6036
    RH https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    N8 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    r4t https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    y4 https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    r2e https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    vv https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:45
    xd https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
    xd https://twenty.orexplore.se/assets/index-DTUxZWpZ.js:47
index-DTUxZWpZ.js:343:152
Download the Apollo DevTools for a better development experience: https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/ index-DTUxZWpZ.js:293:11984
```

Docker Compose log is showing:

```
server_1  | [Nest] 1  - 08/11/2024, 10:03:12 AM     LOG [WorkspaceCacheStorageService] Cache version mismatch detected for workspace 30ee066d-1861-49e8-8331-071ddb3d01a9. Current version: 0. Latest version: 1. Invalidating cache...
server_1  | [Nest] 1  - 08/11/2024, 10:03:12 AM     LOG [TypeDefinitionsGenerator] Generating composite type objects: [LINK, LINKS, CURRENCY, FULL_NAME, ADDRESS, ACTOR]
server_1  | [Nest] 1  - 08/11/2024, 10:03:12 AM     LOG [TypeDefinitionsGenerator] Generating metadata objects: [activityTarget, activity, apiKey, auditLog, attachment, blocklist, calendarEvent, calendarChannel, calendarChannelEventAssociation, calendarEventParticipant, comment, company, connectedAccount, favorite, opportunity, person, timelineActivity, viewField, viewFilter, viewSort, view, webhook, workspaceMember, messageThread, message, messageChannel, messageChannelMessageAssociation, messageParticipant]
server_1  | metadata query time: 1.0013790000230074 ms
server_1  | node:events:492
server_1  |       throw er; // Unhandled 'error' event
server_1  |       ^
server_1  | 
server_1  | Error: ENOENT: no such file or directory, open '/app/packages/twenty-server/.local-storage/workspace-30ee066d-1861-49e8-8331-071ddb3d01a9/workspace-logo/original/014f5e46-697c-4820-a074-6f53f028ac60.png'
server_1  | Emitted 'error' event on ReadStream instance at:
server_1  |     at emitErrorNT (node:internal/streams/destroy:151:8)
server_1  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
server_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
server_1  |   errno: -2,
server_1  |   code: 'ENOENT',
server_1  |   syscall: 'open',
server_1  |   path: '/app/packages/twenty-server/.local-storage/workspace-30ee066d-1861-49e8-8331-071ddb3d01a9/workspace-logo/original/014f5e46-697c-4820-a074-6f53f028ac60.png'
server_1  | }
server_1  | 
server_1  | Node.js v18.17.1
twenty-docker_server_1 exited with code 1
```

I.e. it looks like it's trying to regenerate some cache, but failing and the server is subsequently crashing?

Our docker-compose.yml is as follows:

```
version: "3.7"

services:
  server:
    image: twentycrm/twenty:${TAG}
    volumes:
      - /srv/docker-data/twenty/server-local-data:/app/${STORAGE_LOCAL_PATH:-.local-storage}
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}

      ENABLE_DB_MIGRATIONS: "true"

      SIGN_IN_PREFILLED: ${SIGN_IN_PREFILLED}
      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}

      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      EMAIL_DRIVER: ${EMAIL_DRIVER}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  worker:
    image: twentycrm/twenty:${TAG}
    volumes:
      - /srv/docker-data/twenty/worker-local-data:/app/${STORAGE_LOCAL_PATH:-.local-storage}
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}

      ENABLE_DB_MIGRATIONS: "true"

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}

      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      EMAIL_SYSTEM_ADDRESS: ${EMAIL_SYSTEM_ADDRESS}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      EMAIL_DRIVER: ${EMAIL_DRIVER}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: twentycrm/twenty-postgres:${TAG}
    volumes:
      - /srv/docker-data/twenty/db-data:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: pg_isready -U twenty -d default
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
```
