### ISSUE TITLE
Cannot send emails invitations for team from Twenty CRM using Gmail SMTP

### ISSUE THREAD

**Issue by zayihu** [twentyhq/twenty#6932]
## Bug Description

I deployed Twenty and everything seems to work. But I cannot send emails invitations for team from Twenty CRM using Gmail SMTP, while when I use PHPMailer with same username, password, host and port, I can send emails and receive them. Also I tried sending emails from demo.twenty.com, which also seems to not send any emails invitations. I tried variaty of different emails, Gmail, Outlook, TempMail.

**Example:** 
I go to Members -> Invite by email -> Type or paste email -> click send -> get notification successfully send -> check email for 5 mins, spam folder and inbox, nothing is send, no email at all.

## Expected behavior

I want to get emails invite SMTP emails from Twenty to emails in input.

**Example:** 
I go to Members -> Invite by email -> Type or paste email -> click send -> get notification successfully send -> check email inbox and spam folder and see email from Twenty.

### From .env
```
EMAIL_FROM_ADDRESS=*******@gmail.com
EMAIL_FROM_NAME="Random from Twenty CRM"
EMAIL_DRIVER=smtp
EMAIL_SMTP_HOST=smtp.gmail.com
EMAIL_SMTP_PORT=465
EMAIL_SMTP_USER=*******@gmail.com
EMAIL_SMTP_PASSWORD="app password"
```
### In docker-compose.yml (partly config)
```
 server:
    image: ${DOCKER_REPOSITORY}/twenty:latest
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    networks:
      proxy:
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${SERVER_HOST}
      LETSENCRYPT_HOST: ${SERVER_HOST}
      ENABLE_DB_MIGRATIONS: "false"
      SIGN_IN_PREFILLED: ${SIGN_IN_PREFILLED}
      STORAGE_TYPE: ${STORAGE_TYPE}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      LOGIN_TOKEN_EXPIRES_IN: ${LOGIN_TOKEN_EXPIRES_IN}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      EMAIL_DRIVER: ${EMAIL_DRIVER}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_ID}
worker:
    image: ${DOCKER_REPOSITORY}/twenty:latest
    command: >
      bash -c "
      yarn worker:prod &&
      yarn command:prod cron:messaging:messages-import &&
      yarn command:prod cron:messaging:message-list-fetch &&
      yarn command:prod cron:calendar:calendar-event-list-fetch"
    environment:
      PG_DATABASE_URL: postgres://twenty:twenty@${PG_DATABASE_HOST}/default
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${SERVER_HOST}
      LETSENCRYPT_HOST: ${SERVER_HOST}
      MESSAGE_QUEUE_TYPE: ${MESSAGE_QUEUE_TYPE}
      ENABLE_DB_MIGRATIONS: "true"
      STORAGE_TYPE: ${STORAGE_TYPE}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      LOGIN_TOKEN_EXPIRES_IN: ${LOGIN_TOKEN_EXPIRES_IN}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}
      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      EMAIL_DRIVER: ${EMAIL_DRIVER}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      MESSAGING_PROVIDER_GMAIL_ENABLED: ${MESSAGING_PROVIDER_GMAIL_ENABLED}
      CALENDAR_PROVIDER_GOOGLE_ENABLED: ${CALENDAR_PROVIDER_GOOGLE_ENABLED}
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_ID}
```
