### ISSUE TITLE
Notes Creation Bug: Unable to Save Title or Content

### ISSUE THREAD

**Issue by rob-luke** [twentyhq/twenty#7231]
## Bug Description

When attempting to create a new note in Twenty, it often (80% of the time) won't save the title or content. Often it appears like the text is saved, but if you refresh or leave the page and come back its gone.

Steps to reproduce:

Navigate to a company or person profile
- Click on the notes tab
- Click on "New Note" (on the right side of the screen, a new note UI appears)
- Click on the title field and type in a new title
- Hit enter or click outside the text entry box
- An error appears at the bottom of the screen, and the note title is not saved
- The same issue occurs when trying to add content to the note

![image](https://github.com/user-attachments/assets/6a28c384-769f-4d19-ba7d-a69290037584)

## Expected behavior

When entering a title or content for a new note and then clicking outside the text entry box or hitting enter, the note should be saved successfully without any error messages.

## Technical inputs

Current workaround:

- Create a new note
- Refresh the entire page
- The note then appears as an empty note
- Click on it and enter the title and content

I am self hosting the latest release of twenty, and everything else works fine. Please let me know if additional info would help

**Comment by Bonapara** [comment]
Can't reproduce 🤔 @Weiko, does that mean anything to you?

**Comment by rob-luke** [comment]
Would it help if I make a video showing the process?

**Comment by rob-luke** [comment]
@Bonapara thanks for trying to reproduce the bug. Attached is a video demonstrating the notes bug. I also captured an occurance of the notes working correctly. Hope this helps. Let me know if you need any more info

https://github.com/user-attachments/assets/bdf63754-30e3-45bc-9583-8e75b3a7d691

**Comment by Bonapara** [comment]
@ijreilly, do you think this bug is related to @rob-luke environment?

**Comment by ijreilly** [comment]
Hi @rob-luke , thanks for sharing! I was not able to reproduce either, but I see there are some errors thrown when you are navigating so I suppose there is an error while attempting to save. 
Can you try again and share the details of the failing requests from your Network tab? 
It should be a graphql query with an "error" in the response payload. 
<img width="1455" alt="Capture d’écran 2024-09-30 à 11 50 13" src="https://github.com/user-attachments/assets/f0523b40-6e27-4cea-b454-e35f48c382a2">

**Comment by rob-luke** [comment]
Thanks @ijreilly and @Bonapara for helping look in to this.
I have updated to the latest release v0.30.2 and still the bug occurs.

I am not experienced with debugging this type of software, so please excuse if I sent too much or the wrong info below. 

Here are two images of the error. I can't see an error in the response payload. But I screenshoted what was red in the network tab.

Does this help?

<img width="2396" alt="Screenshot 2024-10-03 at 9 01 41 PM" src="https://github.com/user-attachments/assets/c4e6102b-af5a-4495-938b-7a34b9261214">
<img width="2393" alt="Screenshot 2024-10-03 at 9 02 06 PM" src="https://github.com/user-attachments/assets/a0fd4ecf-757a-42da-88f6-05a71fa5eebd">

Also, here is my docker-compose setup (I replaced sensitive data with `AAAAA`):


```
version: "3.8"

services:


  twenty:
    image: twentycrm/twenty:v0.30.2
    volumes:
      - /home/AAAAA/twenty/server:/app/${STORAGE_LOCAL_PATH:-.local-storage}
      - /home/AAAAA/twentydata/:/app/docker-data
    ports:
      - 3854:3854
    restart: always
    depends_on:
      - twenty-redis
    environment:
      PORT: 3854
      PG_DATABASE_URL: postgres://AAAAA:AAAAA@AAAAA:AAAAA/default
      SERVER_URL: https://AAAAA.AAAAA.com
      FRONT_BASE_URL: https://AAAAA.AAAAA.com

      ENABLE_DB_MIGRATIONS: "true"

      SIGN_IN_PREFILLED: "false"
      IS_SIGN_UP_DISABLED: "false"
      LOGIN_TOKEN_EXPIRES_IN: 90d
      REFRESH_TOKEN_EXPIRES_IN: 14d
      ACCESS_TOKEN_EXPIRES_IN: 30m

      STORAGE_TYPE: s3
      STORAGE_S3_REGION: AAAAA
      STORAGE_S3_NAME: AAAAA
      AWS_ACCESS_KEY_ID: AAAAA
      AWS_SECRET_ACCESS_KEY: AAAAA

      ACCESS_TOKEN_SECRET: AAAAA
      LOGIN_TOKEN_SECRET: AAAAA
      REFRESH_TOKEN_SECRET: AAAAA
      FILE_TOKEN_SECRET: AAAAA

      AUTH_GOOGLE_ENABLED: "true"
      MESSAGING_PROVIDER_GMAIL_ENABLED: "true"
      CALENDAR_PROVIDER_GMAIL_ENABLED: "true"
      CALENDAR_PROVIDER_GOOGLE_ENABLED: "true"
      AUTH_GOOGLE_APIS_CALLBACK_URL: https://AAAAA.AAAAA.com/auth/google-apis/get-access-token
      AUTH_GOOGLE_CALLBACK_URL: https://AAAAA.AAAAA.com/auth/google/redirect
      AUTH_GOOGLE_CLIENT_ID: AAAAA
      AUTH_GOOGLE_CLIENT_SECRET: AAAAA

      REDIS_HOST: AAAAA
      REDIS_PORT: AAAAA
      CACHE_STORAGE_TYPE: redis
      CACHE_STORAGE_TTL: 3600
      MESSAGE_QUEUE_TYPE: bull-mq

  twenty-worker:
    image: twentycrm/twenty:v0.30.2
    volumes:
      - /home/AAAAA/twenty/server:/app/${STORAGE_LOCAL_PATH:-.local-storage}
      - /home/AAAAA/twentydata/:/app/docker-data
    restart: always
    command: yarn worker:prod
    ports:
      - 3855:3855
    depends_on:
      - twenty-redis
      - twenty
    environment:
      PORT: AAAAA
      PG_DATABASE_URL: postgres://AAAAA:AAAAA@AAAAA:AAAAA/default
      SERVER_URL: https://AAAAA.AAAAA.com
      FRONT_BASE_URL: https://AAAAA.AAAAA.com

      ENABLE_DB_MIGRATIONS: "true"
      IS_LINKS_FIELD_ENABLED: "true"

      SIGN_IN_PREFILLED: "false"
      IS_SIGN_UP_DISABLED: "false"
      LOGIN_TOKEN_EXPIRES_IN: 90d
      REFRESH_TOKEN_EXPIRES_IN: 14d
      ACCESS_TOKEN_EXPIRES_IN: 30m

      STORAGE_TYPE: s3
      STORAGE_S3_REGION: AAAAA
      STORAGE_S3_NAME: AAAAA
      AWS_ACCESS_KEY_ID: AAAAA
      AWS_SECRET_ACCESS_KEY: AAAAA

      ACCESS_TOKEN_SECRET: AAAAA
      LOGIN_TOKEN_SECRET: AAAAA
      REFRESH_TOKEN_SECRET: AAAAA
      FILE_TOKEN_SECRET: AAAAA

      AUTH_GOOGLE_ENABLED: "true"
      MESSAGING_PROVIDER_GMAIL_ENABLED: "true"
      CALENDAR_PROVIDER_GMAIL_ENABLED: "true"
      CALENDAR_PROVIDER_GOOGLE_ENABLED: "true"
      AUTH_GOOGLE_APIS_CALLBACK_URL: https://AAAAA.AAAAA.com/auth/google-apis/get-access-token
      AUTH_GOOGLE_CALLBACK_URL: https://AAAAA.AAAAA.com/auth/google/redirect
      AUTH_GOOGLE_CLIENT_ID: AAAAA
      AUTH_GOOGLE_CLIENT_SECRET: AAAAA

      REDIS_HOST: AAAAA
      REDIS_PORT: AAAAA
      CACHE_STORAGE_TYPE: redis
      CACHE_STORAGE_TTL: 3600
      MESSAGE_QUEUE_TYPE: bull-mq

  twenty-redis:
    image: redis
    ports:
      - 6379:6379

```
