### ISSUE TITLE
Adding new database extension fails

### ISSUE THREAD

**Issue by BOHEUS** [twentyhq/twenty#8694]
When running `npx nx database:reset twenty-server`, there are errors in logs about failed creation of extensions

```
> ts-node ./scripts/setup-db.ts

query failed: CREATE EXTENSION IF NOT EXISTS "vector"
error: error: extension "vector" is not available
Failed to perform 'create extension "vector (pgvector)"': QueryFailedError: extension "vector" is not available
Performed 'create schema "public"' successfully
Performed 'create schema "metadata"' successfully
Performed 'create schema "core"' successfully
Performed 'create extension "uuid-ossp"' successfully
Performed 'create extension "postgres_fdw"' successfully
Performed 'create extension "wrappers"' successfully
Performed 'create extension "mysql_fdw"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "airtable_fdw"
          HANDLER "airtable_fdw_handler"
          VALIDATOR "airtable_fdw_validator";

error: error: foreign-data wrapper "airtable_fdw" already exists
Performed 'create airtable "wrappers"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "bigquery_fdw"
          HANDLER "big_query_fdw_handler"
          VALIDATOR "big_query_fdw_validator";

error: error: foreign-data wrapper "bigquery_fdw" already exists
Performed 'create bigQuery "wrappers"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "clickhouse_fdw"
          HANDLER "click_house_fdw_handler"
          VALIDATOR "click_house_fdw_validator";

error: error: foreign-data wrapper "clickhouse_fdw" already exists
Performed 'create clickHouse "wrappers"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "firebase_fdw"
          HANDLER "firebase_fdw_handler"
          VALIDATOR "firebase_fdw_validator";

error: error: foreign-data wrapper "firebase_fdw" already exists
Performed 'create firebase "wrappers"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "logflare_fdw"
          HANDLER "logflare_fdw_handler"
          VALIDATOR "logflare_fdw_validator";

error: error: foreign-data wrapper "logflare_fdw" already exists
Performed 'create logflare "wrappers"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "s3_fdw"
          HANDLER "s3_fdw_handler"
          VALIDATOR "s3_fdw_validator";

error: error: foreign-data wrapper "s3_fdw" already exists
Performed 'create s3 "wrappers"' successfully
query failed:
          CREATE FOREIGN DATA WRAPPER "stripe_fdw"
          HANDLER "stripe_fdw_handler"
          VALIDATOR "stripe_fdw_validator";

error: error: foreign-data wrapper "stripe_fdw" already exists
Performed 'create stripe "wrappers"' successfully
```

**Comment by subson** [comment]
all these extensions do not come enabled by default in postgres installer. I am able to install vector by installing the app version from postgres site but rest of the extensions I am not sure from where to install.

**Comment by BOHEUS** [comment]
@subson this extensions are installed/created automatically when running `npx nx database:reset twenty-server`, I'm running database in Docker container

**Comment by yassinehamouten** [comment]
Hi ! 
have you found a solution?

**Comment by ChristophJeworutzki** [comment]
I’m experiencing the exact same issue.
Running the latest Docker image installed via Coolify.
Does anyone have insights or suggestions to resolve this?

**Comment by trungtin** [comment]
> I’m experiencing the exact same issue. Running the latest Docker image installed via Coolify. Does anyone have insights or suggestions to resolve this?

Go to terminal tab, select Twenty container, then
```bash
mkdir /app/docker-data
touch /app/docker-data/db_status
```
It should work

**Comment by ChristophJeworutzki** [comment]
> > I’m experiencing the exact same issue. Running the latest Docker image installed via Coolify. Does anyone have insights or suggestions to resolve this?
> 
> Go to terminal tab, select Twenty container, then
> 
> mkdir /app/docker-data
> touch /app/docker-data/db_status
> It should work

@trungtin

Thank you for the tip! This seems to work. However, it is not persistent between deployments, unfortunately. I believe the docker-compose file might be outdated and could need an update to address this issue.

You can check the [original docker-compose file here](https://github.com/twentyhq/twenty/blob/main/packages/twenty-docker/docker-compose.yml). Perhaps adjustments to volume mappings or other configurations might help resolve this.

**Comment by jqwez** [comment]
@ChristophJeworutzki  I experienced the same issue in the same environment. I manually edited the docker compose config to pull "v0.32" instead of "latest" and it dodges the error. @trungtin how did you figure out that creating /app/docker-data/db_status fixes the issue?

**Comment by jqwez** [comment]
@ChristophJeworutzki Failed at v0.33.5 and v0.33.4 as well for me. It seens v0.32 performs the touch.

**Comment by jqwez** [comment]
OK, I think the issue originates from the recent entrypoint.sh change

`
# Check if the initialization has already been done and that we enabled automatic migration
if [ "${ENABLE_DB_MIGRATIONS}" = "true" ] && [ ! -f /app/docker-data/db_status ]; then
    echo "Running database setup and migrations..."

    # Creating the database if it doesn't exist
    PGUSER=$(echo $PG_DATABASE_URL | awk -F '//' '{print $2}' | awk -F ':' '{print $1}')
    PGPASS=$(echo $PG_DATABASE_URL | awk -F ':' '{print $3}' | awk -F '@' '{print $1}')
    PGHOST=$(echo $PG_DATABASE_URL | awk -F '@' '{print $2}' | awk -F ':' '{print $1}')
    PGPORT=$(echo $PG_DATABASE_URL | awk -F ':' '{print $4}' | awk -F '/' '{print $1}')
    PGPASSWORD=${PGPASS} psql -h ${PGHOST} -p ${PGPORT} -U ${PGUSER} -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'default'" | grep -q 1 || \
    PGPASSWORD=${PGPASS} psql -h ${PGHOST} -p ${PGPORT} -U ${PGUSER} -d postgres -c "CREATE DATABASE \"default\""

    # Run setup and migration scripts
    NODE_OPTIONS="--max-old-space-size=1500" tsx ./scripts/setup-db.ts
    yarn database:migrate:prod

    # Mark initialization as done
    echo "Successfuly migrated DB!"
    touch /app/docker-data/db_status
fi`

I might be wrong here but maybe with bash set -e if this portion of the script fails such as when tsx ./scripts/setup-db.ts terminates with an error code, the whole program will continually reattempt this entrypoint.sh before getting to touch /app/docker-data/db_status.

**Comment by ChristophJeworutzki** [comment]
@trungtin @jqwez 

I've added a one-off service called `change-vol-ownership` to adjust the ownership of mounted volumes. This service ensures the correct ownership (`1000:1000`) is applied to the following paths, just as specified in the [original docker-compose file](https://github.com/twentyhq/twenty/blob/main/packages/twenty-docker/docker-compose.yml) from the Twenty repository.

- `/tmp/server-local-data`
- `/tmp/docker-data`

This adjustment is necessary for ensuring the application has proper permissions to access and modify these directories. However, since this is a one-off service, it exits upon completion, which causes **Coolify** to flag it as "unhealthy." This happens because Coolify expects services to continuously run or pass a healthcheck, which isn’t applicable for a one-off task.

---

### Suggested Fix
To resolve this issue in Coolify, you can use the **"Exclude from service status"** option in the service settings for `change-vol-ownership`. This will exclude the service from health monitoring, preventing it from being marked as exited or unhealthy. This solution worked for me and ensures proper functionality without unnecessary errors.

---

### Full `docker-compose.yml` Example

Below is the updated `docker-compose.yml` configuration, including the new `change-vol-ownership` service:


``` yml
services:
  change-vol-ownership:
    image: ubuntu
    user: root
    volumes:
      - 'server-local-data:/tmp/server-local-data'
      - 'docker-data:/tmp/docker-data'
    command: "bash -c \" echo 'Changing ownership of /tmp/server-local-data' && chown -R 1000:1000 /tmp/server-local-data && echo 'Changing ownership of /tmp/docker-data' && chown -R 1000:1000 /tmp/docker-data && echo 'Ownership change completed' && exit 0\"  # Exit cleanly with a success status code\n"
    restart: 'no'
  twenty:
    image: 'twentycrm/twenty:latest'
    volumes:
      - 'server-local-data:/app/packages/twenty-server/.local-storage'
      - 'docker-data:/app/docker-data'
    environment:
      - SERVICE_FQDN_TWENTY_3000
      - SERVER_URL=$SERVICE_FQDN_TWENTY
      - FRONT_BASE_URL=$SERVICE_FQDN_TWENTY
      - ENABLE_DB_MIGRATIONS=true
      - 'CACHE_STORAGE_TYPE=${CACHE_STORAGE_TYPE:-redis}'
      - 'REDIS_URL=redis://redis:6379'
      - 'API_RATE_LIMITING_TTL=${API_RATE_LIMITING_TTL:-100}'
      - 'API_RATE_LIMITING_LIMIT=${API_RATE_LIMITING_LIMIT:-100}'
      - APP_SECRET=$SERVICE_BASE64_32_SECRET
      - POSTGRES_ADMIN_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'PG_DATABASE_URL=postgres://postgres:$SERVICE_PASSWORD_POSTGRES@postgres:5432/default'
      - 'IS_SIGN_UP_DISABLED=${IS_SIGN_UP_DISABLED:-false}'
      - 'PASSWORD_RESET_TOKEN_EXPIRES_IN=${PASSWORD_RESET_TOKEN_EXPIRES_IN:-5m}'
      - WORKSPACE_INACTIVE_DAYS_BEFORE_NOTIFICATION=$WORKSPACE_INACTIVE_DAYS_BEFORE_NOTIFICATION
      - WORKSPACE_INACTIVE_DAYS_BEFORE_DELETION=$WORKSPACE_INACTIVE_DAYS_BEFORE_DELETION
      - 'STORAGE_TYPE=${STORAGE_TYPE:-local}'
      - STORAGE_S3_REGION=$STORAGE_S3_REGION
      - STORAGE_S3_NAME=$STORAGE_S3_NAME
      - STORAGE_S3_ENDPOINT=$STORAGE_S3_ENDPOINT
      - STORAGE_S3_ACCESS_KEY_ID=$STORAGE_S3_ACCESS_KEY_ID
      - STORAGE_S3_SECRET_ACCESS_KEY=$STORAGE_S3_SECRET_ACCESS_KEY
      - 'MESSAGE_QUEUE_TYPE=${MESSAGE_QUEUE_TYPE:-pg-boss}'
      - EMAIL_FROM_ADDRESS=$EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME=$EMAIL_FROM_NAME
      - EMAIL_SYSTEM_ADDRESS=$EMAIL_SYSTEM_ADDRESS
      - 'EMAIL_DRIVER=${EMAIL_DRIVER:-logger}'
      - EMAIL_SMTP_HOST=$EMAIL_SMTP_HOST
      - EMAIL_SMTP_PORT=$EMAIL_SMTP_PORT
      - EMAIL_SMTP_USER=$EMAIL_SMTP_USER
      - EMAIL_SMTP_PASSWORD=$EMAIL_SMTP_PASSWORD
      - SIGN_IN_PREFILLED=false
      - 'DEBUG_MODE=${DEBUG_MODE:-false}'
      - 'TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}'
      - MESSAGING_PROVIDER_GMAIL_ENABLED=true
      - CALENDAR_PROVIDER_GOOGLE_ENABLED=true
      - AUTH_GOOGLE_APIS_CALLBACK_URL=${AUTH_GOOGLE_APIS_CALLBACK_URL}
      - AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
      - AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}
      - AUTH_GOOGLE_CALLBACK_URL=${AUTH_GOOGLE_CALLBACK_URL}
      - FRONT_AUTH_CALLBACK_URL=${FRONT_AUTH_CALLBACK_URL}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000/healthz'
      interval: 2s
      timeout: 10s
      retries: 15
  postgres:
    image: 'twentycrm/twenty-postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - POSTGRES_DB=default
    volumes:
      - 'pg-data:/bitnami/postgresql'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: 'redis:latest'
    volumes:
      - 'redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 20s
      retries: 10
```
