### ISSUE TITLE
Docker Compose Upgrade to 0.34 breaks Redirect

### ISSUE THREAD

**Issue by chrisjenx** [twentyhq/twenty#9031]
## Bug Description

Upgrade to 0.34.0 from 0.33.7 breaks redirect, i.e. https://twenty.domain.com will redirect to localhost/welcome instead of the set `SERVER_URL` in the .env file

## Expected behavior

Should respect the `.env` `SERVER_URL=` setting for docker compose apps

## Technical inputs

Followed upgrade instructions. docker compose down -> docker compose up -d 
Everything is running and no errors in logs... guessing it's not reading the env file correctly?

**Comment by FelixMalfait** [comment]
Hey @chrisjenx thanks for trying out 0.34 so quickly. We'll get back to you with a solution tomorrow

**Comment by charlesBochet** [comment]
@chrisjenx @FelixMalfait the upgrade guide is missing, FRONT_DOMAIN, FRONT_PROTOCOL (and FRONT_PORT) need to be specified

**Comment by chrisjenx** [comment]
So yes, adding FRONT_DOMAIN and FRONT_PROTOCOL to .env and docker-compose fixes getting to the front end.

Looks like it doesn't auto migrate the database tho, we now get:

`ApolloError: column Workspace.subdomain does not exist` when trying to login with email/password

**Comment by kbkozlev** [comment]
I have the same issue.
Is "front_domain" the same as "server_url" and with protocol is it "https" or something else?

**Comment by FelixMalfait** [comment]
Hey @kbkozlev you can see examples at the top of this PR: https://github.com/twentyhq/twenty/pull/9034/files

Based on your feedback we've now made FRONT_DOMAIN/PROTOCOL optional (we just need to publish a new tag) and we fallback on the SERVER_URL if it isn't defined. That way we don't complexify the setup for most instances which have the same frontend/backend url

Thanks @chrisjenx for the report!

**Comment by chrisjenx** [comment]
Thanks! do you want a different ticket for the `ApolloError: column Workspace.subdomain does not exist when trying to login with email/password` error?

**Comment by chrisjenx** [comment]
Fixed, now get:
![Image](https://github.com/user-attachments/assets/b1f784cf-cad8-4090-947a-08d7c8db7923)

**Comment by FelixMalfait** [comment]
@chrisjenx that's strange because it should be in the entrypoint command when you restart the docker: https://github.com/twentyhq/twenty/blob/2ceb1c87b3d7a79486883e6f3ce8c133030ba169/packages/twenty-docker/twenty/entrypoint.sh#L18 

Can you check `ENABLE_DB_MIGRATIONS`'s value maybe?

**Comment by chrisjenx** [comment]
@FelixMalfait 

It's there, I can try running manually as well I guess

```
  server:
    image: twentycrm/twenty:${TAG}
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PG_DATABASE_URL: postgres://${PGUSER_SUPERUSER:-postgres}:${PGPASSWORD_SUPERUSER:-twenty}@${PG_DATABASE_HOST:-db:5432}/default
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${FRONT_BASE_URL:-$SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

      ENABLE_DB_MIGRATIONS: "true"
```
